Blog/urls.py
# _*_ encoding:utf-8 _*_
"""Blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import xadmin


from users.views import IndexView, TypesView, TagsView, ArcticleDetailView, PostCommentView, ArchiveView, SearchView

urlpatterns = [
    #后台管理
    path('admin/', admin.site.urls),
    # path('xadmin/', xadmin.site.urls),
    #首页
    path('', IndexView.as_view(), name='index'),
    #分类页
    path('types/', TypesView.as_view(), name='types'),
    #标签页
    path('tags/', TagsView.as_view(), name='tags'),
    #文章详情
    url(r'^article/(?P<article_id>\d+)/$', ArcticleDetailView.as_view(), name='article'),
    # 发表评论
    path('post_comment/<int:article_id>/', PostCommentView.as_view(), name='post_comment'),
    # #关于我
    # path('about/', AboutView.as_view(), name='about'),
    #归档
    url(r'^archives/$', ArchiveView.as_view(), name='archives'),
    #搜索
    url(r'^search/$', SearchView.as_view(), name='search'),
    #配置markdown
    url(r'mdeditor/', include('mdeditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

articles/models.py
# _*_ encoding:utf-8 _*_
from django.db import models
from datetime import datetime
from mdeditor.fields import MDTextField

from users.models import UserProfile, UserFree
# Create your models here.


class Type(models.Model):
    name = models.CharField(verbose_name=u'分类名称', max_length=20)

    class Meta:
        verbose_name = u'分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(verbose_name=u'标签名称', max_length=20)

    class Meta:
        verbose_name = u'标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ArticleManager(models.Manager):
    def distinct_date(self):
        distinct_date_list = []
        date_list = self.values('createtime').order_by('-createtime')
        for date in date_list:
            date = date['createtime'].strftime('%y')
            if date not in distinct_date_list:
                distinct_date_list.append(date)
        return distinct_date_list


class Article(models.Model):
    title = models.CharField(verbose_name=u'标题', max_length=50)
    type = models.ForeignKey(Type, verbose_name=u'文章类型', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name=u'文章标签')
    user = models.ForeignKey(UserProfile, verbose_name=u'作者', on_delete=models.CASCADE)
    desc = models.CharField(max_length=200, default='', verbose_name=u'概要')
    content = MDTextField(verbose_name=u'内容', default='')
    firstPicture = models.ImageField(verbose_name=u'首图', max_length=100, upload_to='picture/%Y/%m',)
    flag = models.CharField(verbose_name=u'标记', max_length=20, choices=((u'原创', u'原创'), (u'原创', u'转载'), (u'翻译', u'翻译')), default=u'原创')
    views = models.IntegerField(default=0, verbose_name=u'浏览次数')
    appreciate = models.IntegerField(default=0, verbose_name=u'赞赏次数')
    share = models.IntegerField(default=0, verbose_name=u'分享次数')
    published = models.BooleanField(verbose_name=u'是否发布', default=False)
    recommend = models.BooleanField(verbose_name=u'是否推荐', default=False)
    createtime = models.DateTimeField(verbose_name=u'创建时间', default=datetime.now)
    updatetime = models.DateTimeField(verbose_name=u'更新时间', default=datetime.now)
    objects = ArticleManager()

    class Meta:
        verbose_name = u'文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class UnPublishedArticle(Article):
    class Meta:
        verbose_name = u'待更文章'
        verbose_name_plural = verbose_name
        proxy = True


class Comment(models.Model):
    article = models.ForeignKey(Article, verbose_name=u'文章', on_delete=models.CASCADE)
    user = models.ForeignKey(UserFree, verbose_name=u'免费用户', default='', related_name='comments', on_delete=models.DO_NOTHING)
    root = models.ForeignKey('self', verbose_name=u'根评论', related_name='root_comment', null=True,blank=True, on_delete=models.DO_NOTHING)
    parent = models.ForeignKey('self', verbose_name=u'上级评论', related_name='parent_comment', null=True, blank=True, on_delete=models.CASCADE)
    reply_to = models.ForeignKey(UserFree, verbose_name=u'回复给', related_name='replies', null=True,blank=True, on_delete=models.DO_NOTHING)
    content = models.TextField(verbose_name=u'评论内容', default='')
    createtime = models.DateTimeField(verbose_name=u'评论时间', default=datetime.now)

    class Meta:
        verbose_name = u'评论'
        verbose_name_plural = verbose_name

templates/archive.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}归档{% endblock %}
{% block content %}
    <!-- blog side -->
    <section class="blog-side sp-seven blog-style-one standard-post sec-pad">
    {% regroup article_list by createtime.year as year_article_group %}
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-12 col-xs-12 content-side">
                        <ul>
                          {% for year in year_article_group %}
                              <div class="text-center" id="{{ year.grouper }}"><h2>{{ year.grouper }} 年</h2></div>
                            {% regroup year.list by createtime.month as month_article_group %}
                            <ul>
                              {% for month in month_article_group %}
                                  <div id="{{ month.grouper }}"><li><h3>{{ month.grouper }} 月</h3></li></div>
                                  <hr style=" height:1px;border:none;border-top:1px dotted grey;" />
                                <ul>
                                  {% for article in month.list %}
                                      <div class="single-post">
                                        <h4><a href="{% url 'article' article.id %}">{{ article.title }}</a></h4>
                                          <h6><p>{{ article.desc }}...</p></h6>
                                        <div class="lower-content" style="">
                                          {% for tag in article.tags.all %}
                                           <div class="meta-text" style="margin-left: 1px; margin-top: 2px;"><a href="{% url 'tags' %}?tag={{ tag.id }}">{{ tag.name }}</a></div>
                                          {% endfor %}
                                        </div>
                                      </div>
                                      <hr style=" height:1px;border:none;border-top:1px dotted grey;" />
                                  {% endfor %}
                                </ul>
                              {% endfor %}
                            </ul>
                          {% endfor %}
                        </ul>
                </div>
                <div class="col-md-3 col-sm-12 col-xs-12 sidebar-side">
                    <div><h2>目录</h2></div>
                       <ul>
                       <li>
                          {% for year in year_article_group %}
                              <a href="#{{ year.grouper }}" style="font-size: large">{{ year.grouper }} 年</a>
                                {% regroup year.list by createtime.month as month_article_group %}
                                <ul>
                                  {% for month in month_article_group %}
                                      <li>
                                      <a href="#{{ month.grouper }}" style="font-size: large">{{ month.grouper }} 月</a>
                                      </li>
                                  {% endfor %}
                                </ul>
                          </li>
                          {% endfor %}
                        </ul>
                       </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- blog side end -->
{% endblock %}

templates/blogs.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}博客详情{% endblock %}
{% block content %}
<!-- blog side -->
    <section class="blog-side sp-seven blog-style-one standard-post sec-pad">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-12 col-xs-12 content-side">
                    <div class="blog-details-content">
                        <figure><img src="{{ MEDIA_URL }}{{ article.firstPicture }}" class="center" alt=""></figure>
                        <div class="blog-content-one sp-three">
                            <div class="top-content centred">
                                <div class="meta-text">{{ article.flag }}</div>
                                <div class="title"><h3>{{ article.title }}</h3></div>
                                <div class="date"><span>On</span> {{ article.createtime }} &nbsp;&nbsp;<i class="flaticon-circle"></i>&nbsp;&nbsp;<span>By</span> {{ article.user.nickname }}</div>
                            </div>
                            <div class="text-style-one">
                                <p id="post_content">{{ article.content|safe }}
                                </p>
                            </div>
                            <ul class="meta-list centred">
                                <li><a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i>&nbsp; {{ article.comment_set.count }}</a> &nbsp; <i class="flaticon-circle"></i> &nbsp; <a href="#"><i class="fa fa-eye" aria-hidden="true"></i>&nbsp; {{ article.views }}</a></li>
                                <li><a href="post1.html"><i class="flaticon-substract"></i> &nbsp; END &nbsp; <i class="flaticon-substract"></i></a></li>
                                <li><a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i> &nbsp;分享</a></li>
                            </ul>
                        </div>
                        <div class="single-authore">
                            <div class="authore-img"><figure><img src="{{ MEDIA_URL }}{{ article.user.avatar }}" style="width: 70px;height: 70px;" alt=""></figure></div>
                            <div class="authore-title">{{ article.user.nickname }} - <span>作者</span></div>
                            <div class="text"><p>bun|sunq</p></div>
                            <ul class="social-link">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                            </ul>
                        </div>
                        <div class="related-post centred">
                            <div class="title-text-two">相关文章</div>
                            <div class="carousel-style-four nav-style-none dots-style-one">
                                {% for related_article in related_articles %}
                                <div class="carousel-style-one">
                                    <figure><img src="{{ MEDIA_URL }}{{ related_article.firstPicture }}" style="height: 200px;" alt=""></figure>
                                    <div class="lower-content">
                                        <div class="meta-text"><a href="#">{{ related_article.type.name }}</a></div>
                                        <div class="title"><h6><a href="post2.html">{{ related_article.title }}</a></h6></div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="comment-area" id="comment-area">
                        <div fr></div>
                            <div class="title-text-two">{{ article.comment_set.count }} 条评论</div>
                            <!--评论根-->
                            {% for comment in comments %}
                            <div class="single-comment">
                                <div class="img-box"><figure><img src="{{ MEDIA_URL }}{{ comment.user.avatar }}" style="width: 80px;height: 80px;" alt=""></figure></div>
                                <div class="comment-title">{{ comment.user.nickname }}</div>
                                <div class="replay"><a href="javascript:reply({{ comment.id }})"><i class="fa fa-reply-all" aria-hidden="true"></i>&nbsp;回复</a></div>
                                <div class="comment-time">{{ comment.createtime }}</div>
                                <div class="text">
                                    <p>{{ comment.content }}</p>
                                </div>
                            </div>
                                <!--评论子-->
                                {% for reply in comment.root_comment.all %}
                                <div class="single-comment replay">
                                    <div class="img-box"><figure><img src="{{ MEDIA_URL }}{{ reply.user.avatar }}" style="width: 80px;height: 80px;" alt=""></figure></div>
                                    <div class="comment-title">{{ reply.user.nickname }}</div>
                                    <div class="replay"><a href="javascript:reply({{ reply.id }})"><i class="fa fa-reply-all" aria-hidden="true"></i>&nbsp;回复</a></div>
                                    <div class="comment-time">{{ reply.createtime }}</div>
                                    <div class="text">
                                        <p>{{ reply.content }}</p>
                                     </div>
                                 </div>
                                 {% endfor %}
                            {% endfor %}
                        </div>
                        <div class="comment-form" id="comment-form">
                            <input type="hidden" value="0" name="reply_comment_id" id="reply_comment_id">
                            <div class="title-text-two">填写评论</div>
                            <form action="{% url 'post_comment' article.id %}" method="post">
                                <div class="row">
                                    <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                        <textarea placeholder="请在这里输入您的评论..." id="content" name="content" required=""></textarea>
                                    </div>
                                    <div class="form-group col-md-6 col-sm-12 col-xs-12">
                                        <input type="text" id="nickname" name="nickname" value="" placeholder="姓名" required="">
                                    </div>
                                    <div class="form-group col-md-6 col-sm-12 col-xs-12">
                                        <input type="email" id="email" name="email" value="" placeholder="邮箱" required="">
                                    </div>
                                    <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                        <button type="button" id="commentpost_btn" class="btn-one">发表评论</button>
                                    </div>
                                </div>
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-12 col-xs-12 sidebar-side">
                <div class="sidebar-categories">
                    <div class="sidebar-title">目录</div>
                       <ul class="categories-list">
                                {{ toc|safe }}
                       </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
<!-- blog side end -->
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}搜索结果{% endblock %}
{% block content %}
    <!-- blog side -->
    <section class="blog-side blog-style-one">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-12 col-xs-12 content-side">
                    <div class="blog-details-content">
                    {% if search_number != 0 %}
                        <p>搜索结果: 共{{ search_number }}条</p>
                        <div class="row">
                            {% for article in search_list.object_list %}
                            <div class="single-blog-content content-box overlay-item">
                                <div class="row">
                                    <div class="col-md-5 col-sm-5 col-xs-12">
                                        <div class="inner-box img-box">
                                            <div class="image-box">
                                                <figure class="image"><img src="{{ MEDIA_URL }}{{ article.firstPicture }}" style="height: 200px" alt=""></figure>
                                                <div class="overlay-box">
                                                    <div class="overlay-inner">
                                                        <div class="content">
                                                            <a href="{% url 'article' article.id %}"><i class="fa fa-link"></i></a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-7 col-sm-7 col-xs-12">
                                        <div class="blog-content-one blog-content-two">
                                            <div class="top-content">
                                                <div class="meta-text"><a href="#">{{ article.type.name }}</a></div>
                                                <div class="title"><h4><a href="post1.html">{{ article.title }}</a></h4></div>
                                                <div class="date"><span>On</span> {{ article.createtime }} &nbsp;&nbsp;<i class="flaticon-circle"></i>&nbsp;&nbsp;<span>By</span> {{ article.user.nickname }}</div>
                                            </div>
                                            <div class="text">
                                                <p>{{ article.desc }}...</p>
                                            </div>
                                            <ul class="meta-list centred">
                                                <li><a href="{% url 'article' article.id %}"><i class="fa fa-comments-o" aria-hidden="true"></i>&nbsp; {{ article.comment_set.count }}</a> &nbsp; <i class="flaticon-circle"></i> &nbsp; <a href="#"><i class="fa fa-eye" aria-hidden="true"></i>&nbsp; {{ article.views }}</a></li>
                                                <li><a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i> &nbsp;分享</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <ul class="page-pagination centred">
                            {% if search_list.has_previous %}
                            <li><a href="?{{ search_list.previous_page_number.querystring }}"><i class="fa fa-angle-left"></i>&nbsp;&nbsp;&nbsp;上一页</a></li>
                            {% endif %}
                            {% for page in search_list.pages %}
                                {% if page %}
                                    {% ifequal page search_list.number %}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                    <li class="none"><a href="">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if search_list.has_next %}
                            <li><a href="?{{ search_list.next_page_number.querystring }}">下一页&nbsp;&nbsp;&nbsp;<i class="fa fa-angle-right"></i></a></li>
                            {% endif %}
                        </ul>
                    {% else %}
                        <p>暂无数据</p>
                    {% endif %}
                    </div>
                </div>
                <div class="col-md-3 col-sm-12 col-xs-12 sidebar-side">
                    <div class="sidebar-content">
                        <div class="sidebar-about centred">
                            <div class="sidebar-title">关于我</div>
                            <figure class="img-box"><a href="about.html"><img src="{% static 'images/default.jpg' %}" alt=""></a></figure>
                            <div class="name"><a href="about.html">SmilexBuns</a></div>
                            <div class="text"><p></p></div>
                            <ul class="social-link">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                            </ul>
                        </div>
                        <div class="sidebar-post">
                            <div class="sidebar-title">今天天气</div>
                            <div class="single-post">
                                <div class="img-box" style="border-radius: 35px;"><figure>
                                    <img  src="{% if today.type == '晴' %}
                                       {% static 'weather/d00.gif' %}
                                       {% elif today.type == '多云' %}
                                       {% static 'weather/d01.gif' %}
                                       {% elif weather.type == '阴' %}
                                       {% static 'weather/d02.gif' %}
                                       {% elif weather.type == '阵雨' %}
                                       {% static 'weather/d03.gif' %}
                                       {% elif today.type == '雷阵雨' %}
                                       {% static 'weather/d04.gif' %}
                                       {% elif weather.type == '雷阵雨伴有冰雹' %}
                                       {% static 'weather/d05.gif' %}
                                       {% elif today.type == '雨夹雪' %}
                                       {% static 'weather/d06.gif' %}
                                       {% elif weather.type == '小雨' %}
                                       {% static 'weather/d07.gif' %}
                                       {% elif weather.type == '中雨' %}
                                       {% static 'weather/d08.gif' %}
                                       {% elif today.type == '大雨' %}
                                       {% static 'weather/d09.gif' %}
                                       {% elif weather.type == '暴雨' %}
                                       {% static 'weather/d10.gif' %}
                                       {% elif today.type == '大暴雨' %}
                                       {% static 'weather/d11.gif' %}
                                       {% elif weather.type == '特大暴雨' %}
                                       {% static 'weather/d12.gif' %}
                                       {% elif today.type == '阵雪' %}
                                       {% static 'weather/d13.gif' %}
                                       {% elif today.type == '小雪' %}
                                       {% static 'weather/d14.gif' %}
                                       {% elif today.type == '中雪' %}
                                       {% static 'weather/d15.gif' %}
                                       {% elif today.type == '大雪' %}
                                       {% static 'weather/d16.gif' %}
                                       {% elif today.type == '暴雪' %}
                                       {% static 'weather/d17.gif' %}
                                       {% elif today.type == '雾' %}
                                       {% static 'weather/d18.gif' %}
                                       {% elif today.type == '冻雨' %}
                                       {% static 'weather/d19.gif' %}
                                       {% elif today.type == '沙尘暴' %}
                                       {% static 'weather/d20.gif' %}
                                       {% elif today.type == '小雨转中雨' %}
                                       {% static 'weather/d21.gif' %}
                                       {% elif today.type == '中雨转大雨' %}
                                       {% static 'weather/d22.gif' %}
                                       {% elif today.type == '大雨转大暴雨' %}
                                       {% static 'weather/d23.gif' %}
                                       {% elif today.type == '暴雨转大暴雨' %}
                                       {% static 'weather/d24.gif' %}
                                       {% elif today.type == '大暴雨转特大暴雨' %}
                                       {% static 'weather/d25.gif' %}
                                       {% elif today.type == '小雪转中雪' %}
                                       {% static 'weather/d26.gif' %}
                                       {% elif today.type == '中雪转大雪' %}
                                       {% static 'weather/d27.gif' %}
                                       {% elif today.type == '大雪转暴雪' %}
                                       {% static 'weather/d28.gif' %}
                                       {% elif today.type == '浮尘' %}
                                       {% static 'weather/d29.gif' %}
                                       {% elif today.type == '扬沙' %}
                                       {% static 'weather/d30.gif' %}
                                       {% elif today.type == '强沙尘暴' %}
                                       {% static 'weather/d31.gif' %}
                                       {% elif today.type == '霾' %}
                                       {% static 'weather/d32.gif' %}
                                    {% endif %}" class="" style="height: 70px;" alt=""></figure></div>
                                <h5>{{ today.type }}</h5>
                                <h6>{{ today.high }} ~ {{ today.low }}</h6>
                                <h6>{{ today.fengxiang }}</h6>
                                <h6>{{ tip }}</h6>
                            </div>
                        </div>
                        <div class="sidebar-categories">
                            <div class="sidebar-title">分类</div>
                            <ul class="categories-list">
                                {% for type in types %}
                                <li><a href="?type={{ type.id }}">{{ type.name }}<span>({{ type.article_set.count }})</span></a></li>
                                {% endfor %}
                                <li><a href="{% url 'types' %}">更多...</a></li>
                            </ul>
                        </div>
                        <div class="sidebar-categories">
                            <div class="sidebar-title">标签</div>
                            <ul class="categories-list">
                                {% for tag in tags %}
                                <li><a href="?tag={{ tag.id }}">{{ tag.name }}<span>({{ tag.article_set.count }})</span></a></li>
                                {% endfor %}
                                <li><a href="{% url 'tags' %}">更多...</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- blog side end -->
{% endblock %}